name: Go




on:
  push: 
    branches: ["main"]

jobs:

  build: 
    runs-on: ubuntu-latest
    steps:
    - name: fetch your code
      uses: actions/checkout@v4
    
    - name: login to docker hub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -P ${{Ssecrets.DOCKER_PASSWORD}}
    
    - name: build docker image
      run : docker build -t ${{secrets.DOCKER_USERNAME}}/awsdeployment .
    
    - name: push docker image
      run: docker push ${{secrets.DOCKER_USERNAME}}/awsdeployment:latest

      

  -